### ISSUE TITLE
[help wanted] Unable to start containers with maestro

### ISSUE THREAD

**Issue by anutham-b** [shoonoise/cabot-docker#18]
Getting the following error:

```shell
fqe@monitoring-fqe:~/cabot-docker$ sudo python3.4 -m maestro -f maestro.yml start
Traceback (most recent call last):
  File "/home/fqe/.local/lib/python3.4/site-packages/maestro/maestro.py", line 250, in _audit_play
    play.run()
  File "/home/fqe/.local/lib/python3.4/site-packages/maestro/plays/__init__.py", line 145, in run
    self._start()
  File "/home/fqe/.local/lib/python3.4/site-packages/maestro/plays/__init__.py", line 115, in _start
    .format(*BaseOrchestrationPlay.HEADERS))
ValueError: Invalid format specifier

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fqe/.local/lib/python3.4/site-packages/maestro/__main__.py", line 209, in execute
    getattr(c, options.command)(**vars(options))
  File "/home/fqe/.local/lib/python3.4/site-packages/maestro/maestro.py", line 332, in start
    ignore_dependencies, concurrency, reuse))
  File "/home/fqe/.local/lib/python3.4/site-packages/maestro/maestro.py", line 262, in _audit_play
    exceptions.raise_with_tb()
TypeError: raise_with_tb() missing 1 required positional argument: 'info'
```

What am I missing ? Running on Ubuntu 14.04 server

**Comment by shoonoise** [comment]
@anutham-b Hi!
I guess it's some mismatch of `maestro`/`python`/`docker-py` versions. Check out signalfuse/maestro-ng#27 issue.

I have [done](https://github.com/shoonoise/cabot-docker/commit/70711c554cbba78e7103bcc838bf5695f8535e8e) moving from `maestro-ng` to `docker-compose`, so the issue should be fixed.
