### ISSUE TITLE
Error while wheeling distribute.

### ISSUE THREAD

**Issue by tschak909** [shoonoise/cabot-docker#29]
While doing the build:

``````
Step 4 : RUN curl -OL https://raw.github.com/pypa/pip/master/contrib/get-pip.py
 ---> Running in 1ab0c1da8f18
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1379k  100 1379k    0     0   741k      0  0:00:01  0:00:01 --:--:-- 3843k
 ---> c580a288289c
Removing intermediate container 1ab0c1da8f18
Step 5 : RUN python get-pip.py
 ---> Running in 05cc6fe41f5c
Collecting pip
  Downloading pip-7.1.2-py2.py3-none-any.whl (1.1MB)
Collecting setuptools
  Downloading setuptools-19.2-py2.py3-none-any.whl (463kB)
Collecting wheel
  Downloading wheel-0.26.0-py2.py3-none-any.whl (63kB)
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-7.1.2 setuptools-19.2 wheel-0.26.0
 ---> 832c82513237
Removing intermediate container 05cc6fe41f5c
Step 6 : RUN git clone https://github.com/arachnys/cabot.git /cabot
 ---> Running in e5e1a54370e5
Cloning into '/cabot'...
 ---> 618755c26580
Removing intermediate container e5e1a54370e5
Step 7 : ADD fixture.json /cabot/
 ---> 20eea9bb6a17
Removing intermediate container e77cb385e347
Step 8 : ADD run.sh /cabot/
 ---> fba6f5cecee1
Removing intermediate container a30bf9721554
Step 9 : ADD gunicorn.conf /cabot/gunicorn.conf
 ---> 7e49e006e8d3
Removing intermediate container 19fe78e2311e
Step 10 : RUN pip install -e /cabot/
 ---> Running in 28c4fb36cd3c
Obtaining file:///cabot
Collecting Django==1.6.8 (from cabot==0.0.1.dev0)
  Downloading Django-1.6.8-py2.py3-none-any.whl (6.7MB)
Collecting Markdown==2.5 (from cabot==0.0.1.dev0)
  Downloading Markdown-2.5.tar.gz (288kB)
Collecting PyJWT==0.1.2 (from cabot==0.0.1.dev0)
  Downloading PyJWT-0.1.2.tar.gz
Collecting South==1.0 (from cabot==0.0.1.dev0)
  Downloading South-1.0.tar.gz (97kB)
Collecting amqp==1.3.3 (from cabot==0.0.1.dev0)
  Downloading amqp-1.3.3.tar.gz (75kB)
Collecting anyjson==0.3.3 (from cabot==0.0.1.dev0)
  Downloading anyjson-0.3.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): argparse==1.2.1 in /usr/lib/python2.7 (from cabot==0.0.1.dev0)
Collecting billiard==3.3.0.13 (from cabot==0.0.1.dev0)
  Downloading billiard-3.3.0.13.tar.gz (148kB)
Collecting celery==3.1.7 (from cabot==0.0.1.dev0)
  Downloading celery-3.1.7.tar.gz (1.3MB)
Collecting distribute==0.6.24 (from cabot==0.0.1.dev0)
  Downloading distribute-0.6.24.tar.gz (620kB)
Collecting dj-database-url==0.2.2 (from cabot==0.0.1.dev0)
  Downloading dj-database-url-0.2.2.tar.gz
Collecting django-appconf==0.6 (from cabot==0.0.1.dev0)
  Downloading django-appconf-0.6.tar.gz
Collecting django-celery==3.1.1 (from cabot==0.0.1.dev0)
  Downloading django-celery-3.1.1.tar.gz (75kB)
Collecting django-celery-with-redis==3.0 (from cabot==0.0.1.dev0)
  Downloading django-celery-with-redis-3.0.tar.gz
Collecting django-compressor==1.4 (from cabot==0.0.1.dev0)
  Downloading django_compressor-1.4-py2.py3-none-any.whl (114kB)
Collecting django-filter==0.7 (from cabot==0.0.1.dev0)
  Downloading django_filter-0.7-py2.py3-none-any.whl
Collecting django-jsonify==0.2.1 (from cabot==0.0.1.dev0)
  Downloading django-jsonify-0.2.1.tar.gz
Collecting django-mptt==0.6.0 (from cabot==0.0.1.dev0)
  Downloading django-mptt-0.6.0.tar.gz (89kB)
Collecting django-polymorphic==0.5.6 (from cabot==0.0.1.dev0)
  Downloading django_polymorphic-0.5.6.tar.gz
Collecting django-redis==1.4.5 (from cabot==0.0.1.dev0)
  Downloading django-redis-1.4.5.tar.gz (41kB)
Collecting django-smtp-ssl==1.0 (from cabot==0.0.1.dev0)
  Downloading django-smtp-ssl-1.0.zip
Collecting djangorestframework==2.4.2 (from cabot==0.0.1.dev0)
  Downloading djangorestframework-2.4.2-py2.py3-none-any.whl (192kB)
Collecting gunicorn==18.0 (from cabot==0.0.1.dev0)
  Downloading gunicorn-18.0.tar.gz (366kB)
Collecting gevent==1.0.1 (from cabot==0.0.1.dev0)
  Downloading gevent-1.0.1.tar.gz (1.5MB)
Collecting hiredis==0.1.1 (from cabot==0.0.1.dev0)
  Downloading hiredis-0.1.1.tar.gz
Collecting httplib2==0.7.7 (from cabot==0.0.1.dev0)
  Downloading httplib2-0.7.7.tar.gz (110kB)
Collecting icalendar==3.2 (from cabot==0.0.1.dev0)
  Downloading icalendar-3.2.tar.gz (67kB)
Collecting kombu==3.0.8 (from cabot==0.0.1.dev0)
  Downloading kombu-3.0.8.tar.gz (335kB)
Collecting mock==1.0.1 (from cabot==0.0.1.dev0)
  Downloading mock-1.0.1.tar.gz (818kB)
Collecting psycogreen==1.0 (from cabot==0.0.1.dev0)
  Downloading psycogreen-1.0.tar.gz
Collecting psycopg2==2.5.1 (from cabot==0.0.1.dev0)
  Downloading psycopg2-2.5.1.tar.gz (684kB)
Collecting pytz==2014.10 (from cabot==0.0.1.dev0)
  Downloading pytz-2014.10-py2.py3-none-any.whl (477kB)
Collecting redis==2.9.0 (from cabot==0.0.1.dev0)
  Downloading redis-2.9.0.tar.gz (314kB)
Collecting requests==2.7.0 (from cabot==0.0.1.dev0)
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)
Collecting six==1.5.1 (from cabot==0.0.1.dev0)
  Downloading six-1.5.1-py2.py3-none-any.whl
Collecting twilio==3.4.1 (from cabot==0.0.1.dev0)
  Downloading twilio-3.4.1.tar.gz (42kB)
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in /usr/lib/python2.7 (from cabot==0.0.1.dev0)
Collecting python-dateutil==2.1 (from cabot==0.0.1.dev0)
  Downloading python-dateutil-2.1.tar.gz (152kB)
Collecting django-auth-ldap==1.2.6 (from cabot==0.0.1.dev0)
  Downloading django-auth-ldap-1.2.6.tar.gz (131kB)
Collecting cabot-alert-hipchat (from cabot==0.0.1.dev0)
  Downloading cabot-alert-hipchat-1.7.1.tar.gz
Collecting cabot-alert-twilio (from cabot==0.0.1.dev0)
  Downloading cabot-alert-twilio-1.1.4.tar.gz
Collecting cabot-alert-email (from cabot==0.0.1.dev0)
  Downloading cabot-alert-email-1.3.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/dist-packages (from django-polymorphic==0.5.6->cabot==0.0.1.dev0)
Collecting greenlet (from gevent==1.0.1->cabot==0.0.1.dev0)
  Downloading greenlet-0.4.9.tar.gz (54kB)
Collecting python-ldap>=2.0 (from django-auth-ldap==1.2.6->cabot==0.0.1.dev0)
  Downloading python-ldap-2.4.22.tar.gz (121kB)
Building wheels for collected packages: Markdown, PyJWT, South, amqp, anyjson, billiard, celery, distribute, dj-database-url, django-appconf, django-celery, django-celery-with-redis, django-jsonify, django-mptt, django-polymorphic, django-redis, django-smtp-ssl, gunicorn, gevent, hiredis, httplib2, icalendar, kombu, mock, psycogreen, psycopg2, redis, twilio, python-dateutil, django-auth-ldap, cabot-alert-hipchat, cabot-alert-twilio, cabot-alert-email, greenlet, python-ldap
  Running setup.py bdist_wheel for Markdown
  Stored in directory: /root/.cache/pip/wheels/50/35/1b/c279619dd6ca661b318390140a4d234f21d7cb3222287bcff3
  Running setup.py bdist_wheel for PyJWT
  Stored in directory: /root/.cache/pip/wheels/29/1d/3c/0aa813d251b37abb8250a1d4fc88139239c23c8e76de0b0d6b
  Running setup.py bdist_wheel for South
  Stored in directory: /root/.cache/pip/wheels/77/78/82/ceaed0f6104119fcbf71245bf64809ef000c3c9b7ec3bf2094
  Running setup.py bdist_wheel for amqp
  Stored in directory: /root/.cache/pip/wheels/20/c3/a2/0d25dcf85cca5702f4a363ac3d4cda809487e21d2e40de7499
  Running setup.py bdist_wheel for anyjson
  Stored in directory: /root/.cache/pip/wheels/3d/9e/de/9bd4afad0b092b039d7b6414f34a1350c53f0bc15fa6bf0647
  Running setup.py bdist_wheel for billiard
  Stored in directory: /root/.cache/pip/wheels/35/a6/0f/20ce2dc8dd76b240a4ed8e54b0f5a3f03676bf7cb6a4448bd5
  Running setup.py bdist_wheel for celery
  Stored in directory: /root/.cache/pip/wheels/b6/c4/02/ab7d7437aef4f449ab1b094c73b2ad3732d65b2a777caaa21d
  Running setup.py bdist_wheel for distribute
  Failed building wheel for distribute
  Complete output from command /usr/bin/python -c "import setuptools;__file__='/tmp/pip-build-8IQwj9/distribute/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpmT77t7pip-wheel-:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Running setup.py bdist_wheel for dj-database-url
  Stored in directory: /root/.cache/pip/wheels/2d/e6/db/7cc51b32a485e55706d7ceb168bf48b85f9d93e4ceaa26beed
  Running setup.py bdist_wheel for django-appconf
  Stored in directory: /root/.cache/pip/wheels/c5/97/44/a02bca424bc6186d6cdc7a05550131948be138e7dbfc164c53
  Running setup.py bdist_wheel for django-celery
  Stored in directory: /root/.cache/pip/wheels/32/a4/cc/ee71ed018455477562118d3a3c637337d371f85fe5f12948d4
  Running setup.py bdist_wheel for django-celery-with-redis
  Stored in directory: /root/.cache/pip/wheels/9f/a3/38/5698aed141f266dc289eef4f51856f178cddf0013d4615528e
  Running setup.py bdist_wheel for django-jsonify
  Stored in directory: /root/.cache/pip/wheels/d2/de/69/4e1392f285c0cd56a8986248b1dcf98d06d0177066c70d7d8c
  Running setup.py bdist_wheel for django-mptt
  Stored in directory: /root/.cache/pip/wheels/6d/db/91/96ff12347b66be4fb3baf747ede09efe68b3f6bfd9a68abca8
  Running setup.py bdist_wheel for django-polymorphic
  Stored in directory: /root/.cache/pip/wheels/a7/22/5d/8a0b5642f04f8f5f2d1df47209190e9a6b526f592b040f71d4
  Running setup.py bdist_wheel for django-redis
  Stored in directory: /root/.cache/pip/wheels/fb/65/0c/0b5759c695fd6304b9e0555c81790643c4c60529f088696fe8
  Running setup.py bdist_wheel for django-smtp-ssl
  Stored in directory: /root/.cache/pip/wheels/98/fa/e2/b156e51d1d2216be311985dea9e87aa5d1b7d27b72b667c7dc
  Running setup.py bdist_wheel for gunicorn
  Stored in directory: /root/.cache/pip/wheels/5f/15/28/7167655816980c19e34e28261f0880b86cd0fe89df6cf354a8
  Running setup.py bdist_wheel for gevent
  Stored in directory: /root/.cache/pip/wheels/f8/61/a2/cf4697cfe4d370862c853c5e46fac4f11d0b9b22667dd6e196
  Running setup.py bdist_wheel for hiredis
  Stored in directory: /root/.cache/pip/wheels/95/0b/1e/da583971a7defd991df0bdcc424130bab8c2cec04d1f2c9e10
  Running setup.py bdist_wheel for httplib2
  Stored in directory: /root/.cache/pip/wheels/8a/f9/a2/bffe4cdb24ffed3fdba5aa846e4b2dda2378201ac0ab9109f2
  Running setup.py bdist_wheel for icalendar
  Stored in directory: /root/.cache/pip/wheels/63/f1/00/571b36981f85d1fe78a866dc42a8230e60d1e764f4c4510325
  Running setup.py bdist_wheel for kombu
  Stored in directory: /root/.cache/pip/wheels/2e/f4/04/1ddaf0bf9bca8b2d30dcf10e1b9f728f00433129897ee06bd6
  Running setup.py bdist_wheel for mock
  Stored in directory: /root/.cache/pip/wheels/c9/b4/72/4de2802cbc4bfd82f938ff92015e1b42f01131583675ab4d00
  Running setup.py bdist_wheel for psycogreen
  Stored in directory: /root/.cache/pip/wheels/70/69/fe/514cd4028d5dc2dddca3b98c61d9cd5d5432c85e0a6b8f28b6
  Running setup.py bdist_wheel for psycopg2
  Stored in directory: /root/.cache/pip/wheels/97/6d/ac/03cc1cd57b7762c094643cd3d098e2835c3ccc3e641b2d6fbb
  Running setup.py bdist_wheel for redis
  Stored in directory: /root/.cache/pip/wheels/36/cf/89/91c04e7fa2fc651a418c77188429795099692a8c07e8e24bfa
  Running setup.py bdist_wheel for twilio
  Stored in directory: /root/.cache/pip/wheels/ee/43/6e/bae931c99a430383ee64922c3fd6f3fac02ca80a24f4648c1a
  Running setup.py bdist_wheel for python-dateutil
  Stored in directory: /root/.cache/pip/wheels/5b/29/45/175ae0165cfd190fd2954de0390495b1282907f47e963f3106
  Running setup.py bdist_wheel for django-auth-ldap
  Stored in directory: /root/.cache/pip/wheels/41/47/94/36379a3ee42e970f9905d7e4101d7bb6ecd14659b3b6fd68d8
  Running setup.py bdist_wheel for cabot-alert-hipchat
  Stored in directory: /root/.cache/pip/wheels/b8/84/f0/dbd1d3cb65247db795bcc2241c503276962b8463ca1e541962
  Running setup.py bdist_wheel for cabot-alert-twilio
  Stored in directory: /root/.cache/pip/wheels/47/50/af/f37d8f465587fd36617192fe50b844764da99055d156ec9562
  Running setup.py bdist_wheel for cabot-alert-email
  Stored in directory: /root/.cache/pip/wheels/16/92/fa/3ee9938f2e7cbcb3ff32e27b203b493e6973793f9b9be26be4
  Running setup.py bdist_wheel for greenlet
  Stored in directory: /root/.cache/pip/wheels/08/9c/52/3d8ee766d654c43b131dcc954f255f8c6270bef617da0ac3e6
  Running setup.py bdist_wheel for python-ldap
  Stored in directory: /root/.cache/pip/wheels/6e/b6/ca/966965eb1376c1b78a204aadee58075da0b47069baca01222b
Successfully built Markdown PyJWT South amqp anyjson billiard celery dj-database-url django-appconf django-celery django-celery-with-redis django-jsonify django-mptt django-polymorphic django-redis django-smtp-ssl gunicorn gevent hiredis httplib2 icalendar kombu mock psycogreen psycopg2 redis twilio python-dateutil django-auth-ldap cabot-alert-hipchat cabot-alert-twilio cabot-alert-email greenlet python-ldap
Failed to build distribute
Installing collected packages: Django, Markdown, PyJWT, South, amqp, anyjson, billiard, pytz, kombu, celery, distribute, dj-database-url, six, django-appconf, django-celery, redis, django-celery-with-redis, django-compressor, django-filter, django-jsonify, django-mptt, django-polymorphic, hiredis, django-redis, django-smtp-ssl, djangorestframework, gunicorn, greenlet, gevent, httplib2, icalendar, mock, psycogreen, psycopg2, requests, twilio, python-dateutil, python-ldap, django-auth-ldap, cabot-alert-hipchat, cabot-alert-twilio, cabot-alert-email, cabot
  Running setup.py install for distribute
  Running setup.py develop for cabot
Successfully installed Django-1.6.8 Markdown-2.5 PyJWT-0.1.2 South-1.0 amqp-1.3.3 anyjson-0.3.3 billiard-3.3.0.13 cabot cabot-alert-email-1.3.1 cabot-alert-hipchat-1.7.1 cabot-alert-twilio-1.1.4 celery-3.1.7 distribute-0.6.24 dj-database-url-0.2.2 django-appconf-0.6 django-auth-ldap-1.2.6 django-celery-3.1.1 django-celery-with-redis-3.0 django-compressor-1.4 django-filter-0.7 django-jsonify-0.2.1 django-mptt-0.6.0 django-polymorphic-0.5.6 django-redis-1.4.5 django-smtp-ssl-1.0 djangorestframework-2.4.2 gevent-1.0.1 greenlet-0.4.9 gunicorn-18.0 hiredis-0.1.1 httplib2-0.7.7 icalendar-3.2 kombu-3.0.8 mock-1.0.1 psycogreen-1.0 psycopg2-2.5.1 python-dateutil-2.1 python-ldap-2.4.22 pytz-2014.10 redis-2.9.0 requests-2.7.0 six-1.5.1 twilio-3.4.1
 ---> baa4bad4361c
Removing intermediate container 28c4fb36cd3c
Step 11 : RUN npm install --no-color -g coffee-script less@1.3 --registry http://registry.npmjs.org/
 ---> Running in 88e9b1add31d
/usr/local/bin/coffee -> /usr/local/lib/node_modules/coffee-script/bin/coffee
/usr/local/bin/cake -> /usr/local/lib/node_modules/coffee-script/bin/cake
/usr/local/bin/lessc -> /usr/local/lib/node_modules/less/bin/lessc
/usr/local/lib
+-- coffee-script@1.10.0
`-- less@1.3.3
  `-- ycssmin@1.0.1

 ---> b19821c53797
Removing intermediate container 88e9b1add31d
Step 12 : ENV PATH $PATH:/cabot/
 ---> Running in c2f2a3a2129c
 ---> f08cbfe8a89b
Removing intermediate container c2f2a3a2129c
Step 13 : ENV PYTHONPATH $PYTHONPATH:/cabot/
 ---> Running in 50f37b026a73
 ---> ea2b108953c5
Removing intermediate container 50f37b026a73
Step 14 : ENV DJANGO_SETTINGS_MODULE cabot.settings
 ---> Running in 5b0ba4f33739
 ---> 7325e00aeb8f
Removing intermediate container 5b0ba4f33739
Step 15 : ENV HIPCHAT_URL https://api.hipchat.com/v1/rooms/message
 ---> Running in c9ede6b4259b
 ---> 73da88d00c7c
Removing intermediate container c9ede6b4259b
Step 16 : ENV LOG_FILE /var/log/cabot
 ---> Running in 2a522d85cfe0
 ---> def2832ed60f
Removing intermediate container 2a522d85cfe0
Step 17 : ENV PORT 5000
 ---> Running in d2f8347bad75
 ---> 892f7a9519fe
Removing intermediate container d2f8347bad75
Step 18 : ENV ADMIN_EMAIL you@example.com
 ---> Running in d30f7284c99b
 ---> 09c43dac8fc8
Removing intermediate container d30f7284c99b
Step 19 : ENV CABOT_FROM_EMAIL noreply@example.com
 ---> Running in a13a6abd539d
 ---> 5e999061ab79
Removing intermediate container a13a6abd539d
Step 20 : ENV DEBUG t
 ---> Running in 0c33f06dab37
 ---> 9ce389e7f916
Removing intermediate container 0c33f06dab37
Step 21 : ENV DB_HOST db
 ---> Running in f6c925c7c37b
 ---> e840fd4825ba
Removing intermediate container f6c925c7c37b
Step 22 : ENV DB_PORT 5432
 ---> Running in 8c0b9319d97c
 ---> b5dbb64ca060
Removing intermediate container 8c0b9319d97c
Step 23 : ENV DB_USER docker
 ---> Running in 2a014ae1d7be
 ---> 2c45ee0e648e
Removing intermediate container 2a014ae1d7be
Step 24 : ENV DB_PASSWORD docker
 ---> Running in c54ec7d187d1
 ---> cd6cbc86c7a8
Removing intermediate container c54ec7d187d1
Step 25 : ENV DJANGO_SECRET_KEY 2FL6ORhHwr5eX34pP9mMugnIOd3jzVuT45f7w430Mt5PnEwbcJgma0q8zUXNZ68A
 ---> Running in 08a79e8b2318
 ---> 9e3ce2f42aa4
Removing intermediate container 08a79e8b2318
Step 26 : ENV WWW_HTTP_HOST cabot.example.com
 ---> Running in 7ca4b32ba243
 ---> cd2d7a52242f
Removing intermediate container 7ca4b32ba243
Step 27 : ENV WWW_SCHEME http
 ---> Running in 718238d70a95
 ---> cd6e3f5605a5
Removing intermediate container 718238d70a95
Step 28 : RUN ln -s /usr/bin/nodejs /usr/bin/node
 ---> Running in 166a489aee85
 ---> c47c967a3320
Removing intermediate container 166a489aee85
Step 29 : EXPOSE 5000
 ---> Running in a0cbd29a344a
 ---> a799dd789cba
Removing intermediate container a0cbd29a344a
Step 30 : WORKDIR /cabot/
 ---> Running in 2180b47d1abc
 ---> e9d8fa7f264a
Removing intermediate container 2180b47d1abc
Step 31 : CMD . /cabot/run.sh
 ---> Running in 71b0ebb278c3
 ---> d8ecb1ff8bef
Removing intermediate container 71b0ebb278c3
Successfully built d8ecb1ff8bef
Creating cabotdockerorig_app_1
Pulling nginx (nginx:latest)...
latest: Pulling from library/nginx
a6e95c2e4006: Pull complete
e5b8ef372059: Pull complete
9fd49db1519a: Pull complete
18fd13acb241: Pull complete
3a13fe6d067c: Pull complete
ad32405e6b07: Pull complete
0d31c477e494: Pull complete
9d0e8e26845f: Pull complete
8c2b81d41510: Pull complete
6bd8695f794a: Pull complete
cb6fb082434e: Already exists
d4b2ba78e3b4: Already exists
library/nginx:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:f732c04f585170ed3bc991e06404bb92504a1d25bfffa0aefd44279f35d1430c
Status: Downloaded newer image for docker.io/nginx:latest

Creating cabotdockerorig_nginx_1
Attaching to cabotdockerorig_celerybroker_1, cabotdockerorig_smtp_1, cabotdockerorig_db_1, cabotdockerorig_app_1, cabotdockerorig_nginx_1
celerybroker_1 | 1:C 13 Jan 00:48:49.285 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
celerybroker_1 |                 _._
celerybroker_1 |            _.-``__ ''-._
celerybroker_1 |       _.-``    `.  `_.  ''-._           Redis 3.0.6 (00000000/0) 64 bit
celerybroker_1 |   .-`` .-```.  ```\/    _.,_ ''-._
celerybroker_1 |  (    '      ,       .-`  | `,    )     Running in standalone mode
celerybroker_1 |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
celerybroker_1 |  |    `-._   `._    /     _.-'    |     PID: 1
celerybroker_1 |   `-._    `-._  `-./  _.-'    _.-'
celerybroker_1 |  |`-._`-._    `-.__.-'    _.-'_.-'|
celerybroker_1 |  |    `-._`-._        _.-'_.-'    |           http://redis.io
celerybroker_1 |   `-._    `-._`-.__.-'_.-'    _.-'
celerybroker_1 |  |`-._`-._    `-.__.-'    _.-'_.-'|
celerybroker_1 |  |    `-._`-._        _.-'_.-'    |
celerybroker_1 |   `-._    `-._`-.__.-'_.-'    _.-'
celerybroker_1 |       `-._    `-.__.-'    _.-'
celerybroker_1 |           `-._        _.-'
celerybroker_1 |               `-.__.-'
celerybroker_1 |
celerybroker_1 | 1:M 13 Jan 00:48:49.305 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
celerybroker_1 | 1:M 13 Jan 00:48:49.305 # Server started, Redis version 3.0.6
celerybroker_1 | 1:M 13 Jan 00:48:49.305 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
celerybroker_1 | 1:M 13 Jan 00:48:49.305 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
celerybroker_1 | 1:M 13 Jan 00:48:49.305 * The server is now ready to accept connections on port 6379
smtp_1         | + sed -ri '
smtp_1         |        s/^#?(dc_local_interfaces)=.*/\1='\''0.0.0.0 ; ::0'\''/;
smtp_1         |        s/^#?(dc_other_hostnames)=.*/\1='\'''\''/;
smtp_1         |        s/^#?(dc_relay_nets)=.*/\1='\''172.17.0.70\/16'\''/;
smtp_1         |        s/^#?(dc_eximconfig_configtype)=.*/\1='\''internet'\''/;
smtp_1         | ' /etc/exim4/update-exim4.conf.conf
smtp_1         | + update-exim4.conf -v
smtp_1         | using non-split configuration scheme from /etc/exim4/exim4.conf.template
smtp_1         |     1 LOG: MAIN
smtp_1         |     1   exim 4.84 daemon started: pid=1, no queue runs, listening for SMTP on port 25 (IPv6 and IPv4)
db_1           | The files belonging to this database system will be owned by user "postgres".
db_1           | This user must also own the server process.
db_1           |
db_1           | The database cluster will be initialized with locale "en_US.utf8".
db_1           | The default database encoding has accordingly been set to "UTF8".
db_1           | The default text search configuration will be set to "english".
db_1           |
db_1           | Data page checksums are disabled.
db_1           |
db_1           | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1           | Success. You can now start the database server using:
db_1           |
db_1           |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1           |
db_1           |
db_1           | WARNING: enabling "trust" authentication for local connections
db_1           | You can change this by editing pg_hba.conf or using the option -A, or
db_1           | --auth-local and --auth-host, the next time you run initdb.
db_1           | waiting for server to start....LOG:  database system was shut down at 2016-01-13 00:49:43 UTC
db_1           | LOG:  MultiXact member wraparound protections are now enabled
db_1           | LOG:  database system is ready to accept connections
db_1           | LOG:  autovacuum launcher started
db_1           |  done
db_1           | server started
db_1           | CREATE DATABASE
db_1           |
db_1           | CREATE ROLE
db_1           |
db_1           |
db_1           | /docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1           |
db_1           | waiting for server to shut down....LOG:  received fast shutdown request
db_1           | LOG:  aborting any active transactions
db_1           | LOG:  autovacuum launcher shutting down
db_1           | LOG:  shutting down
db_1           | LOG:  database system is shut down
db_1           |  done
db_1           | server stopped
db_1           |
db_1           | PostgreSQL init process complete; ready for start up.
db_1           |
db_1           | LOG:  database system was shut down at 2016-01-13 00:49:47 UTC
db_1           | LOG:  MultiXact member wraparound protections are now enabled
db_1           | LOG:  database system is ready to accept connections
db_1           | LOG:  autovacuum launcher started
app_1          | Traceback (most recent call last):
app_1          |   File "manage.py", line 11, in <module>
app_1          |     execute_from_command_line(sys.argv)
app_1          |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
app_1          |     utility.execute()
app_1          |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
app_1          |     self.fetch_command(subcommand).run_from_argv(self.argv)
app_1          |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 261, in fetch_command
app_1          |     commands = get_commands()
app_1          |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 107, in get_commands
app_1          |     apps = settings.INSTALLED_APPS
app_1          |   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
app_1          |     self._setup(name)
app_1          |   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
app_1          |     self._wrapped = Settings(settings_module)
app_1          |   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
app_1          |     % (self.SETTINGS_MODULE, e)
app_1          | ImportError: Could not import settings 'cabot.settings' (Is it on sys.path? Is there an import error in the settings file?): cannot import name _uuid_generate_random
app_1          | Traceback (most recent call last):
app_1          |   File "/usr/local/bin/celery", line 7, in <module>
app_1          |     from celery.__main__ import main
app_1          |   File "/usr/local/lib/python2.7/dist-packages/celery/__init__.py", line 130, in <module>
app_1          |     from .five import recreate_module
app_1          |   File "/usr/local/lib/python2.7/dist-packages/celery/five.py", line 149, in <module>
app_1          |     from kombu.utils.compat import OrderedDict  # noqa
app_1          |   File "/usr/local/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 18, in <module>
app_1          |     from uuid import UUID, uuid4 as _uuid4, _uuid_generate_random
app_1          | ImportError: cannot import name _uuid_generate_random
cabotdockerorig_app_1 exited with code 1
nginx_1        | 2016/01/13 01:30:20 [notice] 1#1: using the "epoll" event method
nginx_1        | 2016/01/13 01:30:20 [notice] 1#1: nginx/1.9.9
nginx_1        | 2016/01/13 01:30:20 [notice] 1#1: built by gcc 4.9.2 (Debian 4.9.2-10)
nginx_1        | 2016/01/13 01:30:20 [notice] 1#1: OS: Linux 3.10.0-327.4.4.el7.x86_64
nginx_1        | 2016/01/13 01:30:20 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx_1        | 2016/01/13 01:30:20 [notice] 1#1: start worker processes
nginx_1        | 2016/01/13 01:30:20 [notice] 1#1: start worker
``````

Am building on Docker version 1.8.2-el7.centos, build a01dc02/1.8.2

Any ideas?

-Thom

**Comment by shoonoise** [comment]
seems like celery issue
http://stackoverflow.com/questions/34198538/cannot-import-name-uuid-generate-random-in-heroku-django
