### ISSUE TITLE
Default username/password: docker/docker doesn't work

### ISSUE THREAD

**Issue by benoror** [shoonoise/cabot-docker#42]
> Default username/password: docker/docker. You can add new users using Django admin interface.

I can't login with these credentials

**Comment by benoror** [comment]
After a bit of research I found no admin user was created, therefore when trying to run `python manage.py loaddata fixture.json` I got this error:

```
root@17afb41de9fc:/cabot# python manage.py loaddata fixture.json
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/cabot/cabot/settings.py", line 6, in <module>
    from cabot.celeryconfig import *
  File "/cabot/cabot/celeryconfig.py", line 4, in <module>
    BROKER_URL = os.environ['CELERY_BROKER_URL']
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'CELERY_BROKER_URL'
```

**Comment by benoror** [comment]
Same issue when trying to run `python manage.py createsuperuser `, as specified in: https://docs.djangoproject.com/en/1.10/intro/tutorial02/#creating-an-admin-user

**Comment by benoror** [comment]
Ok last command failed because I missed setting the env var, after setting them I succesfully ran `python manage.py createsuperuser`, then `python manage.py loaddata fixture.json` failed with: 

```
...
django.db.utils.ProgrammingError: Problem installing fixture '/cabot/fixture.json': Could not load auth.User(pk=1): relation "cabotapp_userprofile" does not exist
LINE 1: INSERT INTO "cabotapp_userprofile" ("user_id", "mobile_numbe...
```

Nevertheless after running `./run.sh` inside an interactive shell the app worked fine

**Comment by benoror** [comment]
After trying to add a new user in Django Admin Panel I get the same error message:

![screen shot 2017-02-07 at 21 26 01](https://cloud.githubusercontent.com/assets/119117/22722358/10f799ca-ed7c-11e6-9ea5-bb6ef7600e40.png)

**Comment by benoror** [comment]
Ok, apparently the root issue is with migrations, running `python manage.py migrate` got these errors:

```
root@17afb41de9fc:/cabot# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/usr/local/lib/python2.7/dist-packages/south/migration/__init__.py", line 173, in migrate_app
    Migrations.calculate_dependencies()
  File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 237, in calculate_dependencies
    migration.calculate_dependencies()
  File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 371, in calculate_dependencies
    for migration in self._get_dependency_objects("depends_on"):
  File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 351, in _get_dependency_objects
    for app, name in getattr(self.migration_class(), attrname, []):
  File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 323, in migration_class
    return self.migration().Migration
  File "/usr/local/lib/python2.7/dist-packages/south/utils/__init__.py", line 62, in method
    value = function(self)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 312, in migration
    raise exceptions.UnknownMigration(self, sys.exc_info())
south.exceptions.UnknownMigration: Migration 'cabot_alert_hipchat:0001_initial' probably doesn't exist.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 310, in migration
    migration = __import__(full_name, {}, {}, ['Migration'])
  File "/usr/local/lib/python2.7/dist-packages/cabot_alert_hipchat/migrations/0001_initial.py", line 4, in <module>
    from django.db import models, migrations
ImportError: cannot import name migrations
```

**Comment by benoror** [comment]
I suspect this might be related to https://github.com/cabotapp/cabot-alert-hipchat/pull/3

**Comment by benoror** [comment]
Ok, apparently this got fixed 2 days ago in https://github.com/arachnys/cabot/commit/a2bf8c9a8251387b094ac04d6f339b4083faae88#diff-7e8e0239ca7a68dd10a7606036d3e114R2

And I created the docker images last week, therefore `requirements-plugins.txt` still had hipchat plugin set to `1.7.0`

---

Also TIL the hard way that Docker will cache git clones 😢 more info:

- http://stackoverflow.com/questions/36996046/how-to-prevent-dockerfile-caching-git-clone
- https://github.com/docker/docker/issues/1996

---

I ended up clearing the whole docker cache:

```
 docker-compose rm --all &&
 docker-compose pull &&
 docker-compose build --no-cache &&
 docker-compose up -d --force-recreate &&

```
- https://github.com/docker/compose/issues/1049#issuecomment-212238105

For some reason migrations still didn't run, so I `docker exec -it` into the container an manually ran them.

Apologies for the spam 🙈

**Comment by shoonoise** [comment]
Hi @benoror 

> Apologies for the spam 🙈

it's ok :)

I tried to build cabot env from scratch and it's works for me after I had removed some surplus options from env file

For some reasons I have no time to update images on docker hub, so best way to set up cabot is:

- git clone the repo
- execute `docker-compose up -d`

In case it's became broken after some time you could try to run `docker-compose build --no-cache && docker-compose up -d`

Feel free to reopen the issue in case it's still reproduces
